/* ============ docket.js — signed PDF delivery dockets (pdf-lib) ============
 *
 * Turns a delivery record (details, received lines, notes, the on-site
 * representative's drawn signature) into a clean A4 delivery docket. Pure:
 * record in, PDF bytes out — aroflo.js owns the flow and the records.
 */
'use strict';

const Docket = (() => {

  const A4 = [595.28, 841.89];
  const M = 48;                       // page margin
  const INK = () => PDFLib.rgb(0.09, 0.11, 0.15);
  const GREY = () => PDFLib.rgb(0.42, 0.45, 0.52);
  const LINE = () => PDFLib.rgb(0.78, 0.8, 0.84);
  const AMBER = () => PDFLib.rgb(0.62, 0.42, 0.03);
  const GREEN = () => PDFLib.rgb(0.13, 0.5, 0.25);

  const qtyStr = q => {
    const n = Number(q) || 0;
    return (Math.round(n * 10000) / 10000).toString();
  };

  // Helvetica is WinAnsi-encoded — anything outside it (arrows, emoji, ticks
  // typed into supplier/notes fields) makes pdf-lib throw. Map what we can,
  // question-mark the rest, and the docket always builds.
  const WINANSI_EXTRA = '–—‘’‚“”„†‡•…‰‹›€™ŒœŠšŽžƒˆ˜';
  const latin = s => String(s == null ? '' : s)
    .replace(/→/g, '->').replace(/[✓✔]/g, 'x').replace(/[\r\n\t]+/g, ' ')
    .split('').map(ch => (ch >= ' ' && ch <= 'ÿ') || WINANSI_EXTRA.includes(ch) ? ch : '?').join('');

  function wrap(font, text, size, maxW) {
    const words = latin(text).split(/\s+/).filter(Boolean);
    const lines = [];
    let cur = '';
    for (const w of words) {
      const t = cur ? cur + ' ' + w : w;
      if (font.widthOfTextAtSize(t, size) <= maxW) { cur = t; continue; }
      if (cur) lines.push(cur);
      let piece = w;
      while (font.widthOfTextAtSize(piece, size) > maxW && piece.length > 2) {
        let cut = piece.length - 1;
        while (cut > 1 && font.widthOfTextAtSize(piece.slice(0, cut), size) > maxW) cut--;
        lines.push(piece.slice(0, cut));
        piece = piece.slice(cut);
      }
      cur = piece;
    }
    if (cur) lines.push(cur);
    return lines.length ? lines : [''];
  }

  async function buildDeliveryPdf(rec) {
    const doc = await PDFLib.PDFDocument.create();
    const reg = await doc.embedFont(PDFLib.StandardFonts.Helvetica);
    const bold = await doc.embedFont(PDFLib.StandardFonts.HelveticaBold);
    const W = A4[0];
    let page, y;

    const footer = () => page.drawText('Generated by AirMark · ' + new Date(rec.when || Date.now()).toLocaleString() + ' · ' + rec.id, {
      x: M, y: M - 20, size: 7.5, font: reg, color: GREY(),
    });
    const newPage = () => { page = doc.addPage(A4); y = A4[1] - M; };
    const ensure = need => { if (y - need < M + 14) { footer(); newPage(); } };
    const text = (s, x, opts = {}) => page.drawText(latin(s), {
      x, y: y - (opts.dy || 0), size: opts.size || 9.5,
      font: opts.bold ? bold : reg, color: opts.color || INK(),
    });
    const rightText = (s, xRight, opts = {}) => {
      const f = opts.bold ? bold : reg;
      const w = f.widthOfTextAtSize(latin(s), opts.size || 9.5);
      text(s, xRight - w, opts);
    };
    const rule = (c, x1 = M, x2 = W - M) => page.drawLine({
      start: { x: x1, y }, end: { x: x2, y }, thickness: 0.7, color: c || LINE(),
    });
    newPage();

    /* header */
    text('DELIVERY DOCKET', M, { size: 19, bold: true, dy: 14 });
    rightText(rec.id, W - M, { size: 12, bold: true, dy: 6 });
    rightText(new Date(rec.when || Date.now()).toLocaleDateString(undefined, { day: 'numeric', month: 'long', year: 'numeric' }), W - M, { size: 9, color: GREY(), dy: 19 });
    y -= 26;
    text('Site delivery record — equipment and parts received on site', M, { size: 9, color: GREY() });
    y -= 12;
    rule();
    y -= 18;

    /* details */
    const meta = [
      ['Supplier', rec.supplier || '—'],
      ['Reference (docket / PO)', rec.ref || '—'],
      ['Received by', rec.receivedBy || '—'],
      ['Site / job', rec.site || '—'],
      ['Stocked into', rec.holder || '— (docket only)'],
      ['Received at', new Date(rec.when || Date.now()).toLocaleString()],
    ];
    const colW = (W - 2 * M) / 2;
    for (let i = 0; i < meta.length; i += 2) {
      let extra = 0;
      for (let c = 0; c < 2 && i + c < meta.length; c++) {
        const x = M + c * colW;
        text(meta[i + c][0].toUpperCase(), x, { size: 6.8, color: GREY() });
        const vals = wrap(bold, meta[i + c][1], 10, colW - 16).slice(0, 2);
        vals.forEach((s, k) => text(s, x, { size: 10, bold: true, dy: 12 + k * 12 }));
        extra = Math.max(extra, (vals.length - 1) * 12);
      }
      y -= 30 + extra;
    }
    y -= 4;

    /* items table */
    const xNum = M, xPn = M + 26, xDesc = M + 148, xQty = W - M;
    const descW = xQty - 54 - xDesc;
    const header = () => {
      text('#', xNum, { size: 8, bold: true, color: GREY() });
      text('PART NO', xPn, { size: 8, bold: true, color: GREY() });
      text('DESCRIPTION', xDesc, { size: 8, bold: true, color: GREY() });
      rightText('QTY RECEIVED', xQty, { size: 8, bold: true, color: GREY() });
      y -= 6;
      rule();
      y -= 13;
    };
    header();
    let units = 0;
    (rec.lines || []).forEach((l, i) => {
      const descLines = wrap(reg, l.desc, 9.5, descW);
      const snLines = l.serial ? wrap(bold, 'S/N ' + l.serial, 8, descW) : [];
      const pnLines = wrap(reg, l.pn || '—', 8.5, xDesc - xPn - 10);
      const extra = (l.stocked ? 0 : 1) + snLines.length;
      const rows = Math.max(descLines.length + extra, pnLines.length);
      ensure(rows * 11.5 + 10);
      text(String(i + 1), xNum, { size: 9, color: GREY() });
      pnLines.forEach((s, k) => text(s, xPn, { size: 8.5, dy: k * 11.5 }));
      descLines.forEach((s, k) => text(s, xDesc, { size: 9.5, dy: k * 11.5 }));
      snLines.forEach((s, k) => text(s, xDesc, { size: 8, bold: true, dy: (descLines.length + k) * 11.5 }));
      if (!l.stocked) text('not a stocked item — listed on this docket only', xDesc, { size: 7.5, color: GREY(), dy: (descLines.length + snLines.length) * 11.5 });
      rightText(qtyStr(l.qty), xQty, { size: 10, bold: true });
      units += Number(l.qty) || 0;
      y -= rows * 11.5 + 4;
      rule(PDFLib.rgb(0.9, 0.91, 0.93));
      y -= 11;
    });
    ensure(24);
    rightText(`${(rec.lines || []).length} line${(rec.lines || []).length === 1 ? '' : 's'} · ${qtyStr(units)} units received`, xQty, { size: 9, bold: true });
    y -= 20;

    /* notes + stock note */
    if (rec.notes) {
      ensure(40);
      text('NOTES / EXCEPTIONS', M, { size: 6.8, color: GREY() });
      y -= 12;
      for (const s of wrap(reg, rec.notes, 9.5, W - 2 * M)) {
        ensure(14);
        text(s, M, { size: 9.5 });
        y -= 12;
      }
      y -= 6;
    }
    ensure(16);
    if (rec.holder && rec.booked) {
      text('Quantities booked into AroFlo stock holder "' + rec.holder + '"' + (rec.bookedAt ? ' at ' + new Date(rec.bookedAt).toLocaleString() : '') + '.', M, { size: 9, color: GREEN() });
    } else if (rec.pending) {
      text('Stock booking pending — these quantities are not in AroFlo yet. Book them from Delivery, Past dockets.', M, { size: 9, color: AMBER() });
    } else {
      text('Docket only — quantities were not booked into AroFlo stock.', M, { size: 9, color: GREY() });
    }
    y -= 30;

    /* signature */
    ensure(150);
    text('RECEIVED IN GOOD ORDER BY (ON-SITE REPRESENTATIVE)', M, { size: 6.8, color: GREY() });
    y -= 8;
    let sigH = 58;
    if (rec.signPng) {
      try {
        const img = await doc.embedPng(rec.signPng);
        const s = Math.min(230 / img.width, 62 / img.height, 1);
        page.drawImage(img, { x: M, y: y - img.height * s, width: img.width * s, height: img.height * s });
        sigH = Math.max(30, img.height * s);
      } catch (e) { /* unreadable signature image — leave the line blank */ }
    }
    y -= sigH + 6;
    rule(LINE(), M, M + 260);
    y -= 13;
    text(rec.signName || '', M, { size: 10, bold: true });
    y -= 12;
    text('Signed ' + new Date(rec.when || Date.now()).toLocaleString(), M, { size: 8, color: GREY() });
    footer();

    return doc.save();
  }

  return { buildDeliveryPdf };
})();
